### ISSUE TITLE
Clicking on Apply button redirects to the same github repository page

### ISSUE THREAD

**Issue by mujjazi** [Lamiiine/Awesome-daily-list-of-visa-sponsored-jobs#3]
**Steps:**

- Visit https://github.com/Lamiiine/Awesome-daily-list-of-visa-sponsored-jobs
-  Click on Apply hyperlink for any job

**Actual Result:**
User is redirected to the same page

**Expected Result:**
User should be redirected to the job posting

**Comment by Lamiiine** [comment]
fixed, thanks Mujjazi
